name: test_ci
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo step1 done
      - name: step2
        run: echo step2 done
      - name: step3
        run: echo step3 done
  job2:

    runs-on: ubuntu-latest
    steps:
      - name: final_check
        run: echo done




#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  workflow_dispatch: